import { Bill } from './types';

const today = new Date();
const d = (offset: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + offset);
  return date.toISOString().split('T')[0];
};

export const mockBills: Bill[] = [
  {
    id: '1',
    description: 'Aluguel escritório coworking',
    supplier: 'WeWork',
    amount: 8500,
    dueDate: d(0),
    paidAt: null,
    status: 'pendente',
    costCenter: 'Administrativo',
    category: 'Aluguel',
    recurrence: 'mensal',
    notes: '',
  },
  {
    id: '2',
    description: 'Google Workspace',
    supplier: 'Google',
    amount: 1200,
    dueDate: d(-3),
    paidAt: null,
    status: 'atrasado',
    costCenter: 'Operação',
    category: 'Software',
    recurrence: 'mensal',
    notes: 'Urgente - acesso do time pode ser cortado',
  },
  {
    id: '3',
    description: 'Campanha Meta Ads - Março',
    supplier: 'Meta',
    amount: 15000,
    dueDate: d(2),
    paidAt: null,
    status: 'pendente',
    costCenter: 'Marketing',
    category: 'Serviços',
    recurrence: 'mensal',
    notes: '',
  },
  {
    id: '4',
    description: 'Folha de pagamento',
    supplier: 'Interno',
    amount: 85000,
    dueDate: d(5),
    paidAt: null,
    status: 'planejado',
    costCenter: 'RH',
    category: 'Salários',
    recurrence: 'mensal',
    notes: 'Inclui 13 colaboradores',
  },
  {
    id: '5',
    description: 'AWS - Infraestrutura Cloud',
    supplier: 'Amazon Web Services',
    amount: 4200,
    dueDate: d(-1),
    paidAt: null,
    status: 'atrasado',
    costCenter: 'Produto',
    category: 'Infraestrutura',
    recurrence: 'mensal',
    notes: '',
  },
  {
    id: '6',
    description: 'Consultoria jurídica',
    supplier: 'Machado & Associados',
    amount: 6000,
    dueDate: d(10),
    paidAt: null,
    status: 'planejado',
    costCenter: 'Jurídico',
    category: 'Consultoria',
    recurrence: 'mensal',
    notes: 'Revisão contratos Q1',
  },
  {
    id: '7',
    description: 'Plano de saúde',
    supplier: 'SulAmérica',
    amount: 12400,
    dueDate: d(7),
    paidAt: null,
    status: 'planejado',
    costCenter: 'RH',
    category: 'Benefícios',
    recurrence: 'mensal',
    notes: '',
  },
  {
    id: '8',
    description: 'HubSpot CRM',
    supplier: 'HubSpot',
    amount: 3800,
    dueDate: d(-5),
    paidAt: d(-5),
    status: 'pago',
    costCenter: 'Vendas',
    category: 'Software',
    recurrence: 'mensal',
    notes: '',
  },
  {
    id: '9',
    description: 'Contabilidade mensal',
    supplier: 'Contabiliza',
    amount: 2800,
    dueDate: d(3),
    paidAt: null,
    status: 'pendente',
    costCenter: 'Administrativo',
    category: 'Serviços',
    recurrence: 'mensal',
    notes: '',
  },
  {
    id: '10',
    description: 'Figma Team',
    supplier: 'Figma',
    amount: 750,
    dueDate: d(12),
    paidAt: null,
    status: 'planejado',
    costCenter: 'Produto',
    category: 'Software',
    recurrence: 'mensal',
    notes: '',
  },
  {
    id: '11',
    description: 'Impostos federais - DAS',
    supplier: 'Receita Federal',
    amount: 9200,
    dueDate: d(1),
    paidAt: null,
    status: 'pendente',
    costCenter: 'Administrativo',
    category: 'Impostos',
    recurrence: 'mensal',
    notes: 'Simples Nacional',
  },
  {
    id: '12',
    description: 'Viagem SP - reunião investidor',
    supplier: 'Latam Airlines',
    amount: 2100,
    dueDate: d(-7),
    paidAt: d(-7),
    status: 'pago',
    costCenter: 'Diretoria',
    category: 'Viagens',
    recurrence: 'única',
    notes: '',
  },
  {
    id: '13',
    description: 'Slack Business+',
    supplier: 'Slack',
    amount: 980,
    dueDate: d(15),
    paidAt: null,
    status: 'planejado',
    costCenter: 'Operação',
    category: 'Software',
    recurrence: 'mensal',
    notes: '',
  },
  {
    id: '14',
    description: 'Treinamento equipe vendas',
    supplier: 'RD Station',
    amount: 4500,
    dueDate: d(20),
    paidAt: null,
    status: 'planejado',
    costCenter: 'Vendas',
    category: 'Consultoria',
    recurrence: 'única',
    notes: 'Workshop de 2 dias',
  },
  {
    id: '15',
    description: 'Energia elétrica',
    supplier: 'CEMIG',
    amount: 680,
    dueDate: d(-2),
    paidAt: null,
    status: 'atrasado',
    costCenter: 'Administrativo',
    category: 'Infraestrutura',
    recurrence: 'mensal',
    notes: '',
  },
];
